steps:
# Install
- name: 'gcr.io/cloud-builders/npm'
  args: ['install']
# Test/Build
- name: 'gcr.io/cloud-builders/npm'
  args: ['run', 'public:myscript.js']
- name: 'gcr.io/cloud-builders/npm'
  args: ['run', 'build']
- name: 'gcr.io/$PROJECT_ID/firebase'
  args: ['deploy']